name: workflow

on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # run once-a-month

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install testing packages
      run: python -m pip install --upgrade pip pytest-cov nbval pycodestyle

    - name: Install package
      run: python -m pip install .

    - name: Unit tests
      run: make test-unittests

    - name: Documentation tests
      run: make test-docs

    - name: Jupyter notebook tests
      run: make test-ipynb

    - name: Python code style
      run: make test-pycodestyle

    - name: Tests coverage
      run: make test-coverage
      if: matrix.os == 'ubuntu-latest'

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
